from .Reward import *
from .BoundsReward import *
from .DeltaDistanceReward import *
from .DistanceReward import *
from .DropAltitudeReward import *
from .FieldCoverageReward import *
from .LandingReward import *
from .OrientationReward import *
from .SlowdownReward import *
from .SpeedReward import *
from .WaypointReward import *
from .cross_obstacles.EnterAreaReward import *
from .cross_obstacles.IncreaseXReward import *
